application: alley-catt
module: default
version: go6
runtime: go
api_version: go1

instance_class: F1
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_concurrent_requests: 50

handlers:
- url: /alleycatt/*
  script: _go_app

#dart webpage


- url: /css/(.*\.(.*))$
  static_files: AlleyCatt/web/\css\1
  upload: AlleyCatt/web/\css\.*\.(.*)$

- url: /js/(.*\.(.*))$
  static_files: AlleyCatt/web/\js\1
  upload: AlleyCatt/web/\js\.*\.(.*)$

# - url: /dart/alleycatt/lib/(.*\.(.*))$
#   static_files: alleycatt/lib/\1
#   upload: alleycatt/lib/.*\.(.*)$

- url: /index.html
  static_files: AlleyCatt/web/index.html
  upload: alleycatt/web/index\.html

# - url: /alleycatt/(.*\.(.*))$
#   static_files: alleycatt/build/web/\1
#   upload: alleycatt/build/web/.*\.(.*)$

# - url: /alleycatt/.*
#   static_files: alleycatt/build/web/index.html
#   upload: alleycatt/build/web/index\.html