application: alley-catt
module: default
version: go6
runtime: go
api_version: go1

instance_class: F1
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_concurrent_requests: 50

handlers:
- url: /alleycatt/*
  script: _go_app

#dart webpage


- url: /css
  static_dir: AlleyCatt/web/css

- url: /js
  static_dir: AlleyCatt/web/js

- url: /images
  static_dir: AlleyCatt/web/images

- url: /fonts
  static_dir: AlleyCatt/web/fonts

# - url: /dart/alleycatt/lib/(.*\.(.*))$
#   static_files: alleycatt/lib/\1
#   upload: AlleyCatt/lib/.*\.(.*)$

- url: /
  static_files: AlleyCatt/web/index.html
  upload: AlleyCatt/web/index\.html

- url: /alleycatt/(.*\.(.*))$
  static_files: AlleyCatt/build/web/\1
  upload: AlleyCatt/build/web/.*\.(.*)$

- url: /(.*\.html)$
  static_files: AlleyCatt/web/\1
  upload: AlleyCatt/web/(.*\.html)$